/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2dpbo;

/**
 *
 * @author sitih
 */



import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class Card extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */
    private dbConnection db;
    private final int id;
    private Menu menu;
    private File myImg;
    private boolean isAlbum = true;
   
    public Card(int id,  Menu menu, boolean isAlbum) {
        initComponents();
        this.db = new dbConnection();
        this.id = id;
        this.menu = menu;
        this.isAlbum = isAlbum;
        if(this.isAlbum){
            setAlbum();
        }else{
            setGrup();
        }
    }
    
    
    public void setAlbum(){
        a1Label.setText("Judul");
        a2Label.setText("Grup");
        a3Label.setText("Harga");
        
        try{
            String sql = "SELECT * FROM album a JOIN grup g ON a.id_grup = g.id_grup WHERE a.id_album = '"+this.id+"'";
            ResultSet res = db.selectQuery(sql);
            while(res.next()){
                a1Field.setText(res.getString("judul"));
                a2Field.setText(res.getString("nama"));
                a3Field.setText(res.getString("harga"));
                BufferedImage fileImg = null;
                this.myImg = new File("src/gambar/Album/"+res.getString("gambar"));
                fileImg = ImageIO.read(this.myImg);
                Image foto = fileImg.getScaledInstance(120, 150,Image.SCALE_SMOOTH);
                img.setIcon(new javax.swing.ImageIcon(foto));
                
            }            
        }catch(SQLException|IOException e){
            System.out.println(e.getMessage());
        }
    }
    
    public void setGrup(){
        a1Label.setText("Nama");
        a2Label.setText("Agensi");
        a3Label.setText("Jumlah Member");
        try{
            String sql = "SELECT * FROM grup WHERE id_grup = '"+this.id+"'";
            ResultSet res = db.selectQuery(sql);
            while(res.next()){
                a1Field.setText(res.getString("nama"));
                a2Field.setText(res.getString("agensi"));
                a3Field.setText(res.getString("jmlh_member"));
                BufferedImage fileImg = null;
                this.myImg = new File("src/gambar/Grup/"+res.getString("gambar"));
                fileImg = ImageIO.read(this.myImg);
                Image foto = fileImg.getScaledInstance(120, 150,Image.SCALE_SMOOTH);
                img.setIcon(new javax.swing.ImageIcon(foto));
            }            
        }catch(SQLException|IOException e){
            System.out.println(e.getMessage());
        }
    }
    
    public void deleteData() {
              // Delete Data in Database
            String sql = this.isAlbum ? "DELETE FROM album WHERE id_album = '"+id+"'" : "DELETE FROM grup WHERE id_grup = '"+id+"'";
            int affectedRow = db.updateQuery(sql);

            if (affectedRow > 0) {
                // hapus img pada folder gambar
                if(myImg != null) myImg.delete();
                // Show Information
                System.out.println("Delete Success");
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } else {   
                JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
            }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        a1Label = new javax.swing.JLabel();
        a1Field = new javax.swing.JTextField();
        a2Label = new javax.swing.JLabel();
        a2Field = new javax.swing.JTextField();
        a3Label = new javax.swing.JLabel();
        a3Field = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        a1Label.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        a1Label.setForeground(new java.awt.Color(0, 51, 51));
        a1Label.setText("Nama");

        a1Field.setBackground(new java.awt.Color(204, 255, 255));
        a1Field.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        a1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1FieldActionPerformed(evt);
            }
        });

        a2Label.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        a2Label.setForeground(new java.awt.Color(0, 51, 51));
        a2Label.setText("Agensi");

        a2Field.setBackground(new java.awt.Color(204, 255, 255));
        a2Field.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        a3Label.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        a3Label.setForeground(new java.awt.Color(0, 51, 51));
        a3Label.setText("Jumlah Member");

        a3Field.setBackground(new java.awt.Color(204, 255, 255));
        a3Field.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        Update.setBackground(new java.awt.Color(153, 153, 255));
        Update.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(0, 153, 204));
        Delete.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(a1Label)
                    .addComponent(a2Label)
                    .addComponent(a3Label)
                    .addComponent(a2Field, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(a1Field)
                    .addComponent(a3Field))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delete)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(a1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void a1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1FieldActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_a1FieldActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        if(isAlbum){
            formAlbum fa = new formAlbum(id,this.menu);
            fa.setVisible(true);
        }else{
            formGrup fg = new formGrup(id,this.menu);
            fg.setVisible(true);
        }
//        System.out.println(id);
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini ?", "Delete Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){ 
           // hapus data
            deleteData() ; 
           // update panel
           this.menu.setPanel();
        }else{
           JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!");   
        
        }
        
        
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JTextField a1Field;
    private javax.swing.JLabel a1Label;
    private javax.swing.JTextField a2Field;
    private javax.swing.JLabel a2Label;
    private javax.swing.JTextField a3Field;
    private javax.swing.JLabel a3Label;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
